### ISSUE TITLE
Changing the interface language doesn't work

### ISSUE THREAD

**Issue by garaga** [shuftipro/Android-SDK#4]
Hi!
I'm using the SDK with OCR, and I'm trying to change the interface language (to German).
`requestBuilder.withLanguage("DE")`

 But the language remains English.

please help me solve this problem.

Thanx!

**Comment by shuftipro** [comment]
Kindly know, the SDK that you are using has been deprecated. Please use the new sdk. Moreover, currently, we are not supporting localization. However, your feedback has been taken into account, so we'll add this in our future release.
