### ISSUE TITLE
Your app is suspended when capture faces or documents automatically

### ISSUE THREAD

**Issue by aiviapp** [shuftipro/Android-SDK#5]
Your app is suspended when capture faces or documents automatically.

**Comment by aaaaasunil** [comment]
After allow external storage permission. Showing a external storage permission denied dialog. How i solve it. Please help me

**Comment by shuftipro** [comment]
Hi @vanhung1710 

We greatly appreciate you taking the time to provide us with your feedback. We wanted to inform you that we have recently released an updated version of our SDK. Your willingness to give it another try and share your valuable insights would be immensely beneficial to us.

Thank you for your consideration.
