### ISSUE TITLE
Permission  issue in android 11 and 12

### ISSUE THREAD

**Issue by aaaaasunil** [shuftipro/Android-SDK#6]
In android 11 and 12 External storage permission not work. I allow it number of time but it say me permission denied. How solve it.

Please help me.

**Comment by shuftipro** [comment]
Hi @aaaaasunil,

We appreciate you providing your feedback.
After a thorough examination of our SDK, we can confirm that it is functioning smoothly on Android 11 and 12. Kindly give it another attempt, and if you encounter the same issue, please provide us with your device information.

Thank you.
